import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

class AppTheme {
  // Available color schemes with beautiful names (matching learning_hub)
  static const Map<String, FlexScheme> schemes = {
    'Material Deep Purple': FlexScheme.material,
    'Blue Delight': FlexScheme.blue,
    'Indigo Nights': FlexScheme.indigo,
    'Green Money': FlexScheme.money,
    'Aqua Blue': FlexScheme.aquaBlue,
    'Brandeis Blue': FlexScheme.brandBlue,
    'Deep Purple': FlexScheme.deepPurple,
    'Ebony Clay': FlexScheme.ebonyClay,
    'Amber Blue': FlexScheme.amber,
    'Vesuvius Burn': FlexScheme.vesuviusBurn,
    'Mandarin Orange': FlexScheme.mandyRed,
    'Hippie Blue': FlexScheme.hippieBlue,
    'Red Wine': FlexScheme.redWine,
    'Green Forest': FlexScheme.green,
    'Blue Whale': FlexScheme.blueWhale,
    'San Juan': FlexScheme.sanJuanBlue,
    'Rosewood': FlexScheme.rosewood,
    'Jungle Green': FlexScheme.jungle,
    'Mallard Green': FlexScheme.mallardGreen,
    'Espresso': FlexScheme.espresso,
  };

  // Get theme based on scheme name
  static ThemeData getTheme({
    required bool isDarkMode,
    required String colorScheme,
  }) {
    // Get the FlexScheme from the map, default to Material if not found
    final scheme = schemes[colorScheme] ?? FlexScheme.material;
    
    if (isDarkMode) {
      return FlexThemeData.dark(
        scheme: scheme,
        useMaterial3: true,
        surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
        blendLevel: 15,
        appBarStyle: FlexAppBarStyle.primary,
        appBarOpacity: 0.95,
        appBarElevation: 2,
        transparentStatusBar: true,
        tabBarStyle: FlexTabBarStyle.forAppBar,
        tooltipsMatchBackground: true,
        swapColors: false,
        darkIsTrueBlack: false,
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        subThemesData: const FlexSubThemesData(
          blendOnLevel: 20,
          blendOnColors: false,
          useMaterial3Typography: true,
          useM2StyleDividerInM3: true,
          elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
          elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
          outlinedButtonOutlineSchemeColor: SchemeColor.primary,
          toggleButtonsSchemeColor: SchemeColor.primary,
          segmentedButtonSchemeColor: SchemeColor.primary,
          inputDecoratorSchemeColor: SchemeColor.primary,
          inputDecoratorBackgroundAlpha: 21,
          inputDecoratorRadius: 8.0,
          inputDecoratorUnfocusedHasBorder: true,
          fabUseShape: true,
          fabSchemeColor: SchemeColor.tertiary,
          chipSchemeColor: SchemeColor.primaryContainer,
          cardRadius: 12.0,
          popupMenuRadius: 8.0,
          dialogRadius: 20.0,
          timePickerDialogRadius: 20.0,
          snackBarRadius: 8,
          appBarScrolledUnderElevation: 4.0,
          bottomSheetRadius: 20.0,
          bottomSheetElevation: 4.0,
          bottomSheetModalElevation: 8.0,
          navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
          navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationBarIndicatorSchemeColor: SchemeColor.primary,
          navigationBarIndicatorOpacity: 1.00,
          navigationBarBackgroundSchemeColor: SchemeColor.surface,
          navigationBarElevation: 2.0,
          navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
          navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationRailIndicatorSchemeColor: SchemeColor.primary,
          navigationRailIndicatorOpacity: 1.00,
        ),
      );
    } else {
      return FlexThemeData.light(
        scheme: scheme,
        useMaterial3: true,
        surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
        blendLevel: 7,
        appBarStyle: FlexAppBarStyle.primary,
        appBarOpacity: 0.95,
        appBarElevation: 2,
        transparentStatusBar: true,
        tabBarStyle: FlexTabBarStyle.forAppBar,
        tooltipsMatchBackground: true,
        swapColors: false,
        lightIsWhite: false,
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        subThemesData: const FlexSubThemesData(
          blendOnLevel: 10,
          blendOnColors: false,
          useMaterial3Typography: true,
          useM2StyleDividerInM3: true,
          elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
          elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
          outlinedButtonOutlineSchemeColor: SchemeColor.primary,
          toggleButtonsSchemeColor: SchemeColor.primary,
          segmentedButtonSchemeColor: SchemeColor.primary,
          inputDecoratorSchemeColor: SchemeColor.primary,
          inputDecoratorBackgroundAlpha: 21,
          inputDecoratorRadius: 8.0,
          inputDecoratorUnfocusedHasBorder: true,
          fabUseShape: true,
          fabSchemeColor: SchemeColor.tertiary,
          chipSchemeColor: SchemeColor.primaryContainer,
          cardRadius: 12.0,
          popupMenuRadius: 8.0,
          dialogRadius: 20.0,
          timePickerDialogRadius: 20.0,
          snackBarRadius: 8,
          appBarScrolledUnderElevation: 4.0,
          bottomSheetRadius: 20.0,
          bottomSheetElevation: 4.0,
          bottomSheetModalElevation: 8.0,
          navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
          navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationBarIndicatorSchemeColor: SchemeColor.primary,
          navigationBarIndicatorOpacity: 1.00,
          navigationBarBackgroundSchemeColor: SchemeColor.surface,
          navigationBarElevation: 2.0,
          navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
          navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationRailIndicatorSchemeColor: SchemeColor.primary,
          navigationRailIndicatorOpacity: 1.00,
        ),
      );
    }
  }
}

